version: "3"
services:
  meet:
    build: .
    ports:
      - '3000:3000'
    environment:
      REACT_APP_COMPANY_NAME=$REACT_APP_COMPANY_NAME
      REACT_APP_DAILY_SUBDOMAIN=$REACT_APP_DAILY_SUBDOMAIN
      REACT_APP_COMPANY_URL=$REACT_APP_COMPANY_URL